### ISSUE TITLE
CLI fails to start with:Cannot find module './importers/pivotalCsv'.

### ISSUE THREAD

**Issue by afoltzm** [linearapp/linear-import#21]
Hi! I'm trying to use the cli to import some issues from Jira, but I can't get it to start. Here's a rundown of the issue I'm facing.

### Bug
`yarn cli` fails to start with a TypeScript compilation error.

**stacktrace**
```
~/linear-import/node_modules/ts-node/src/index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/cli.ts:8:34 - error TS2307: Cannot find module './importers/pivotalCsv'.

8 import { pivotalCsvImport } from './importers/pivotalCsv';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/andrew/repos_external/linear-import/node_modules/ts-node/src/index.ts:245:12)
    at reportTSError (/home/andrew/repos_external/linear-import/node_modules/ts-node/src/index.ts:249:19)
    at getOutput (/home/andrew/repos_external/linear-import/node_modules/ts-node/src/index.ts:362:34)
    at Object.compile (/home/andrew/repos_external/linear-import/node_modules/ts-node/src/index.ts:395:32)
    at Module.m._compile (/home/andrew/repos_external/linear-import/node_modules/ts-node/src/index.ts:473:43)
    at Module._extensions..js (module.js:664:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/andrew/repos_external/linear-import/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected behavior: 
`yarn cli` works after `yarn install`

### Steps to reproduce:
1. Clone the repo
2. Run `yarn install` from the repo dir
3. Run `yarn cli` from the repo dir

### Additional information
`Ubuntu 19.10`
`nodejs - v10.15.2` (installed via Nix package manager)
`yarn - v 1.22.4` (installed in userspace with `npm install -g`)

Please let me know if you need additional information from me.

**Comment by ksaa** [comment]
@afoltzm can you make sure you are have the latest version from master? CLI seems to start for me

```
saarinen@ksmp linear-import % git log
commit 9a6b9678c41993a1e367c06900cc5c711f4201a7 (HEAD -> master, origin/master, origin/HEAD)
Merge: e658845 e04c9dc
Author: Jori Lallo <jori@linear.app>
Date:   Fri Apr 10 15:05:27 2020 -0400

```

**Comment by jorilallo** [comment]
@afoltzm looks like there was an issue with case sensitivity with that folder. I fixed it now in `master`

**Comment by afoltzm** [comment]
I was able to successfully import after pulling from master. Thanks! :heavy_check_mark:
